[2025-03-23T19:17:49.236+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T19:17:49.261+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.clean_data manual__2025-03-23T19:10:07.337326+00:00 [queued]>
[2025-03-23T19:17:49.275+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.clean_data manual__2025-03-23T19:10:07.337326+00:00 [queued]>
[2025-03-23T19:17:49.276+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-23T19:17:49.309+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): clean_data> on 2025-03-23 19:10:07.337326+00:00
[2025-03-23T19:17:49.323+0000] {standard_task_runner.py:72} INFO - Started process 135 to run task
[2025-03-23T19:17:49.360+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'clean_data', 'manual__2025-03-23T19:10:07.337326+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpek08p3_3']
[2025-03-23T19:17:49.377+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask clean_data
[2025-03-23T19:17:49.555+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-23T19:17:49.709+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.clean_data manual__2025-03-23T19:10:07.337326+00:00 [running]> on host 22e98b2d0fd5
[2025-03-23T19:17:49.993+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='botorat3@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T19:10:07.337326+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T19:10:07.337326+00:00'
[2025-03-23T19:17:49.996+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T19:17:50.062+0000] {data_pipeline.py:54} INFO - Executing script: /opt/airflow/scripts/data_preprocessing.py
[2025-03-23T19:22:49.478+0000] {data_pipeline.py:56} INFO - Successfully executed: /opt/airflow/scripts/data_preprocessing.py
[2025-03-23T19:22:49.659+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T19:22:50.250+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T19:22:50.270+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=clean_data, run_id=manual__2025-03-23T19:10:07.337326+00:00, execution_date=20250323T191007, start_date=20250323T191749, end_date=20250323T192250
[2025-03-23T19:22:50.761+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T19:22:52.343+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-23T19:22:52.363+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
