[2025-03-23T19:11:37.473+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T19:11:37.489+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_data manual__2025-03-23T19:10:07.337326+00:00 [queued]>
[2025-03-23T19:11:37.499+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_data manual__2025-03-23T19:10:07.337326+00:00 [queued]>
[2025-03-23T19:11:37.500+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-23T19:11:37.523+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data> on 2025-03-23 19:10:07.337326+00:00
[2025-03-23T19:11:37.531+0000] {standard_task_runner.py:72} INFO - Started process 109 to run task
[2025-03-23T19:11:37.535+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'download_data', 'manual__2025-03-23T19:10:07.337326+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpgz6aoae8']
[2025-03-23T19:11:37.541+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask download_data
[2025-03-23T19:11:37.575+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-23T19:11:37.606+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.download_data manual__2025-03-23T19:10:07.337326+00:00 [running]> on host 22e98b2d0fd5
[2025-03-23T19:11:37.694+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='botorat3@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T19:10:07.337326+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T19:10:07.337326+00:00'
[2025-03-23T19:11:37.695+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T19:11:37.715+0000] {data_pipeline.py:54} INFO - Executing script: /opt/airflow/scripts/data_acquisition.py
[2025-03-23T19:13:29.308+0000] {data_pipeline.py:56} INFO - Successfully executed: /opt/airflow/scripts/data_acquisition.py
[2025-03-23T19:13:29.514+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T19:13:30.031+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T19:13:30.050+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_data, run_id=manual__2025-03-23T19:10:07.337326+00:00, execution_date=20250323T191007, start_date=20250323T191137, end_date=20250323T191330
[2025-03-23T19:13:30.484+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T19:13:30.831+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-23T19:13:30.848+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
